---
title: 'Data from: Perceived threats of infanticide reduce maternal allocation during
  lactation and lead to elevated oxidative damage in offspring'
author: Jeff Walker
date: '2019-02-18'
slug: data-from-perceived-threats-of-infanticide-reduce-maternal-allocation-during-lactation-and-lead-to-elevated-oxidative-damage-in-offspring
categories: []
tags:
  - linear mixed model
  - repeated measures anova
  - SPSS
subtitle: ''
output:
  blogdown::html_page:
    toc: true
---


<div id="TOC">
<ul>
<li><a href="#sources">Sources</a></li>
<li><a href="#summary">Summary</a></li>
<li><a href="#caveats">Caveats</a></li>
<li><a href="#setup">Setup</a></li>
<li><a href="#import">Import</a></li>
<li><a href="#reproducibility">Reproducibility</a><ul>
<li><a href="#offspring-weight">Offspring weight</a></li>
<li><a href="#maternal-behaviour">Maternal behaviour</a></li>
<li><a href="#glucocorticoid-metabolites-in-mothers">Glucocorticoid metabolites in mothers</a></li>
<li><a href="#fig.-3">Fig. 3</a></li>
<li><a href="#oxidative-stress-in-offspring">Oxidative stress in offspring</a></li>
</ul></li>
<li><a href="#statistical-red-flags">Statistical Red Flags</a><ul>
<li><a href="#computation-of-anova-table-using-afex-package">1. Computation of ANOVA table using Afex package</a><ul>
<li><a href="#how-balanced-is-the-design">How balanced is the design</a></li>
<li><a href="#anova-using-afex-computation-above">ANOVA using Afex (computation above)</a></li>
</ul></li>
<li><a href="#anova-table-using-lmelmer">3 ANOVA table using lme/lmer</a><ul>
<li><a href="#compare-lmm-to-anova-table-using-lm-and-aov-ignoring-clustering-due-to-repeated-measures">Compare LMM to ANOVA table using lm() and AOV (ignoring clustering due to repeated measures)</a></li>
<li><a href="#plot-it-to-visualize-the-effects">Plot it to visualize the effects</a></li>
</ul></li>
</ul></li>
</ul>
</div>

<div id="sources" class="section level1">
<h1>Sources</h1>
<p>Gale T, Garratt M, Brooks RC (2018) Perceived threats of infanticide reduce maternal allocation during lactation and lead to elevated oxidative damage in offspring. Functional Ecology 32(9): 2158-2169. <a href="https://doi.org/10.1111/1365-2435.13146" class="uri">https://doi.org/10.1111/1365-2435.13146</a></p>
<p>Gale T, Garratt M, Brooks RC (2018) Data from: Perceived threats of infanticide reduce maternal allocation during lactation and lead to elevated oxidative damage in offspring. Dryad Digital Repository. <a href="https://doi.org/10.5061/dryad.762k24f" class="uri">https://doi.org/10.5061/dryad.762k24f</a></p>
</div>
<div id="summary" class="section level1">
<h1>Summary</h1>
<ol style="list-style-type: decimal">
<li>The available data are clean. All data sets are in a single Excel sheet. An issue for reproducibility is that the data set for each experiment is not identified.</li>
<li>In general, most results (that I was able to run) reproduce</li>
<li>One error is in the reporting of the ANOVA statistics for growth rate. Two of the terms are reported with the F and P values for other terms in the table.</li>
<li>The ANOVA for the interaction effects of Sex x Treatment on weight at adulthood do not reproduce.</li>
<li>Oxidative stress cannot be reproduced because the data are incomplete (Two columns, Sex and Plate, were not given)</li>
</ol>
</div>
<div id="caveats" class="section level1">
<h1>Caveats</h1>
<p>Failure to reproduce or partial reproducibility might be an error in my coding, or my misunderstanding of the author’s methods, or my lack of knowledge of statistics generally or the R functions that I use more specifically.</p>
</div>
<div id="setup" class="section level1">
<h1>Setup</h1>
<pre class="r"><code>library(ggplot2)
library(readxl)
library(data.table)
library(emmeans)
library(nlme)
library(lme4)
library(lmerTest)
library(afex)
library(car)</code></pre>
<pre class="r"><code>data_folder &lt;- &quot;../data&quot;
folder &lt;- &quot;Data from Perceived threats of infanticide reduce maternal allocation during lactation and lead to elevated oxidative damage in offspring&quot;

# images need to be moved to /static/images/data from.../image.png
knitr_path &lt;- FALSE # run = TRUE to debug

source(&quot;../R/clean_label.R&quot;) # bookdown</code></pre>
</div>
<div id="import" class="section level1">
<h1>Import</h1>
<p>The single sheet contains all experiments in blocks glued wide</p>
<pre class="r"><code>fn &lt;- &quot;LBE paper data.xlsx&quot;
file_path &lt;- paste(data_folder, folder, fn, sep=&quot;/&quot;)

# offspring weight
exp1 &lt;- data.table(read_excel(file_path, range=&quot;A1:E185&quot;))
colnames(exp1) &lt;- clean_label(colnames(exp1))
exp1[, Treatment:=factor(Treatment)]

exp2 &lt;- data.table(read_excel(file_path, range=&quot;F1:H45&quot;))
colnames(exp2) &lt;- clean_label(colnames(exp2))
exp2[, Treatment:=factor(Treatment)]

# maternal behavior
exp3 &lt;- data.table(read_excel(file_path, range=&quot;K1:U45&quot;))
colnames(exp3) &lt;- clean_label(colnames(exp3))
exp3[, Treatment:=factor(Treatment)]

# GCMs
exp4 &lt;- data.table(read_excel(file_path, range=&quot;V1:Z60&quot;))
colnames(exp4) &lt;- clean_label(colnames(exp4))
exp4[, Treatment:=factor(Treatment)]

#oxidative stress
exp5 &lt;- data.table(read_excel(file_path, range=&quot;AA1:AJ86&quot;))
colnames(exp5) &lt;- clean_label(colnames(exp5))
exp5[, Treatment:=factor(Treatment)]</code></pre>
</div>
<div id="reproducibility" class="section level1">
<h1>Reproducibility</h1>
<div id="offspring-weight" class="section level2">
<h2>Offspring weight</h2>
<blockquote>
<p>The mean birth weight of novel male treatment pups (1.619± 0.432g) was not significantly different from that of the familiar male treatment (1.628 ± 0.433g; ANOVA: weight: F1, 182= 0.022, p= 0.882; litter size: F1,42= 0.070, p= 0.792).</p>
</blockquote>
<pre class="r"><code># birth weight
exp1[,.(birth=mean(birth),
        SD=sd(birth),
        SE=sd(birth)/sqrt(.N)), by=Treatment]</code></pre>
<pre><code>##    Treatment    birth        SD         SE
## 1:       LBE 1.619080 0.4321785 0.04633439
## 2:        MC 1.628012 0.4331604 0.04398077</code></pre>
<pre class="r"><code>anova(lm(birth ~ Treatment, data=exp1))</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: birth
##            Df Sum Sq  Mean Sq F value Pr(&gt;F)
## Treatment   1  0.004 0.003659  0.0195  0.889
## Residuals 182 34.075 0.187226</code></pre>
<pre class="r"><code># litter size
anova(lm(Littersize ~ Treatment, data=exp2))</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: Littersize
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Treatment  1  0.061 0.06098  0.0702 0.7923
## Residuals 42 36.484 0.86868</code></pre>
<p>Reproduces, the error is sample SD and not SEM.</p>
<p>and identifies LBE = novel male treatment, MC = familiar male treatment</p>
<blockquote>
<p>To analyse the differences in offspring growth rate we used repeated measures ANOVA reporting within-subjects effects. Mauchly’s Test of Sphericity indicated that the assumption of sphericity had been violated (χ2(2) = 34.210, p = &lt;0.001), therefore degrees of freedom were corrected using Greenhouse-Geisser adjusted degrees of freedom. There was a difference in growth rate between the treatments but there was no effect of sex (treatment: F1.7,310=7.49, p= 0.001; interaction between treatment and time: F1.7,310=5668, p= &lt;0.001; sex x treatment: F1.6,306=1.3, p= 0.270).</p>
</blockquote>
<p>A treatment effect on growth rate is indirectly indicated by treatment x time interaction.</p>
<pre class="r"><code>exp1[, ID:=factor(1:nrow(exp1))]
exp1[, Treatment:=factor(Treatment, c(&quot;MC&quot;, &quot;LBE&quot;))]
exp1[, Sex:=factor(Sex)]
exp1_long &lt;- melt(exp1, id.vars = c(&quot;Treatment&quot;, &quot;Sex&quot;, &quot;ID&quot;), variable.name=&quot;Time&quot;, value.name = &quot;Weight&quot;)
exp1_long[, ID:=factor(ID)]
#(fit.aov_car &lt;- aov_car(Weight ~ Treatment*Sex*Time + Error(ID/Time), data=exp1_long))
#(fit.ez &lt;- aov_ez(&quot;ID&quot;, &quot;Weight&quot;, exp1_long, between=c(&quot;Treatment&quot;, &quot;Sex&quot;), within=&quot;Time&quot;))
(fit.aov_4 &lt;- aov_4(Weight ~ Treatment*Sex*Time + (Time|ID), data=exp1_long))</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: Treatment, Sex</code></pre>
<pre><code>## Anova Table (Type 3 tests)
## 
## Response: Weight
##               Effect           df  MSE           F   ges p.value
## 1          Treatment       1, 180 1.85     7.30 **   .02    .008
## 2                Sex       1, 180 1.85        0.36 .0009     .55
## 3      Treatment:Sex       1, 180 1.85      5.60 *   .01     .02
## 4               Time 1.70, 306.53 1.20 5670.13 ***   .94  &lt;.0001
## 5     Treatment:Time 1.70, 306.53 1.20     7.57 **   .02    .001
## 6           Sex:Time 1.70, 306.53 1.20        1.28  .004     .28
## 7 Treatment:Sex:Time 1.70, 306.53 1.20        2.27  .007     .11
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;+&#39; 0.1 &#39; &#39; 1
## 
## Sphericity correction method: GG</code></pre>
<p>I think it generally reproduces but I think the authors have mixed up the terms in their reporting.</p>
<ol style="list-style-type: decimal">
<li>The authors report the treatment x time interaction as F1.7,310=5668, p= &lt;0.001, which 1) is a huge F given what the interaction effect looks like and is nearly equivalent to my stats for the Time term.</li>
<li>The authors report sex x treatment: F1.6,306=1.3, p= 0.270 which is very close to my sex x time term.</li>
</ol>
<p>The unbalanced design raises statistical red flag #1</p>
<blockquote>
<p>This resulted in novel male treatment pups being significantly smaller (7.19±0.61g), at weaning (4 weeks old) (ANOVA: F1,182=27.11, p=&lt;0.001) than the familiar male treatment pups (7.99±1.48g)</p>
</blockquote>
<pre class="r"><code>m1 &lt;- lm(weaning ~ Treatment, data=exp1)
anova(m1)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: weaning
##            Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## Treatment   1  29.327 29.3271  27.107 5.168e-07 ***
## Residuals 182 196.908  1.0819                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>exp1[, .(weaning=mean(weaning),
         SD=sd(weaning),
         SE=sd(weaning)/sqrt(.N)),
     by=.(Treatment)]</code></pre>
<pre><code>##    Treatment  weaning        SD         SE
## 1:       LBE 7.199425 0.7886084 0.08454769
## 2:        MC 7.999072 1.2222930 0.12410505</code></pre>
<p>The means reproduce but not the sample SD.</p>
<blockquote>
<p>there were no weight differences at adulthood (13 weeks old) (ANOVA: F1, 184=0.760, p=0.384)</p>
</blockquote>
<pre class="r"><code>anova(lm(adulthood ~ Treatment, data=exp1))</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: adulthood
##            Df Sum Sq Mean Sq F value Pr(&gt;F)
## Treatment   1   2.04  2.0411  0.7604 0.3843
## Residuals 182 488.53  2.6842</code></pre>
<p>reproduces</p>
<blockquote>
<p>There were also no significant interactions of treatment and sex in weight at weaning (sex x treatment F1,180= 2.14, p=0.145) or at adulthood (sex x treatment F1, 180=0.044, p=0.868)).</p>
</blockquote>
<pre class="r"><code>anova(lm(weaning ~ Sex*Treatment, data=exp1))</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: weaning
##                Df  Sum Sq Mean Sq F value   Pr(&gt;F)    
## Sex             1   0.620  0.6205  0.5762   0.4488    
## Treatment       1  29.468 29.4683 27.3644 4.65e-07 ***
## Sex:Treatment   1   2.307  2.3067  2.1421   0.1451    
## Residuals     180 193.839  1.0769                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>anova(lm(adulthood ~ Sex*Treatment, data=exp1))</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: adulthood
##                Df Sum Sq Mean Sq F value  Pr(&gt;F)  
## Sex             1   0.31  0.3146  0.1190 0.73051  
## Treatment       1   2.02  2.0166  0.7629 0.38360  
## Sex:Treatment   1  12.43 12.4283  4.7017 0.03145 *
## Residuals     180 475.81  2.6434                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The weaning results reproduce. The adulthood results do not. Here is a plot of the interaction.</p>
<pre class="r"><code>(fit.emm &lt;- data.table(summary(emmeans(lm(adulthood ~ Sex*Treatment, data=exp1),
                   specs=c(&quot;Sex&quot;, &quot;Treatment&quot;)))))</code></pre>
<pre><code>##    Sex Treatment   emmean        SE  df lower.CL upper.CL
## 1:   F        MC 13.21312 0.2254647 180 12.76822 13.65801
## 2:   M        MC 12.80000 0.2423672 180 12.32175 13.27825
## 3:   F       LBE 12.52708 0.2346711 180 12.06402 12.99014
## 4:   M       LBE 13.15933 0.2603442 180 12.64561 13.67305</code></pre>
<pre class="r"><code>setnames(fit.emm, old=&quot;emmean&quot;, new=&quot;adulthood&quot;)
pd &lt;- position_dodge(0.5)
gg &lt;- ggplot(data=exp1, aes(x=Treatment, y=adulthood, color=Sex, group=Sex)) +
  #geom_point(position=pd) +
  geom_point(data=fit.emm, aes(y=adulthood), position=pd)+
  geom_errorbar(data=fit.emm, aes(ymin=lower.CL, ymax=upper.CL), position=pd, width=0.2) +
  geom_line(data=fit.emm, position=pd) +
  NULL
gg</code></pre>
<p><img src="/post/2019-02-18-data-from-perceived-threats-of-infanticide-reduce-maternal-allocation-during-lactation-and-lead-to-elevated-oxidative-damage-in-offspring_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<div id="maternal-behaviour" class="section level2">
<h2>Maternal behaviour</h2>
<blockquote>
<p>There was no significant difference in the amount of time the mothers spent in nest, grooming, licking pups, eating/ drinking, nest building, resting or active (Table 1). The only behaviour showing significant differences between treatments was nursing, with females exposed to familiar males spent almost twice the time nursing (Table 1).</p>
</blockquote>
<pre class="r"><code>y_list &lt;- c(&quot;In_Nest&quot;, &quot;Nursing&quot;, &quot;Licking_Pups&quot;, &quot;Nest_Building&quot;, &quot;Eating.Drinking&quot;, &quot;Grooming&quot;, &quot;Active&quot;, &quot;Resting&quot;)
my_table &lt;- data.table(NULL)
exp3[, one:=1] # used for getting N in each level
exp3[, myID:=factor(1:.N)] # ID 164 is present twice
for(y in y_list){
  n.mc &lt;- sum(exp3[Treatment==&quot;MC&quot; &amp; !is.na(get(y)), one])
  n.lbe &lt;- sum(exp3[Treatment==&quot;LBE&quot; &amp; !is.na(get(y)), one])
  fixed_i &lt;- formula(paste(y, &quot;Treatment&quot;, sep=&quot; ~ &quot;))
  my_table &lt;- rbind(my_table, 
                 data.table(Response=y, 
                            anova(lme(fixed_i, random = ~ 1|Block,
                                      method=&quot;ML&quot;, data=exp3))[2,],
                            Mean.MC=mean(exp3[Treatment==&quot;MC&quot;, get(y)]),
                            SE.MC=sd(exp3[Treatment==&quot;MC&quot;, get(y)])/sqrt(n.mc),
                            Mean.LBE=mean(exp3[Treatment==&quot;LBE&quot;, get(y)]),
                            SE.LBE=sd(exp3[Treatment==&quot;LBE&quot;, get(y)])/sqrt(n.lbe)
                 ))
}
# table is printed below the reported table</code></pre>
<p><img src="/images/Data%20from%20Perceived%20threats%20of%20infanticide%20reduce%20maternal%20allocation%20during%20lactation%20and%20lead%20to%20elevated%20oxidative%20damage%20in%20offspring/table1.png" /><!-- --></p>
<table>
<thead>
<tr class="header">
<th align="left">Response</th>
<th align="right">numDF</th>
<th align="right">denDF</th>
<th align="right">F-value</th>
<th align="right">p-value</th>
<th align="right">Mean.MC</th>
<th align="right">SE.MC</th>
<th align="right">Mean.LBE</th>
<th align="right">SE.LBE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">In_Nest</td>
<td align="right">1</td>
<td align="right">41</td>
<td align="right">3.89</td>
<td align="right">0.055</td>
<td align="right">114.35</td>
<td align="right">4.16</td>
<td align="right">103.48</td>
<td align="right">3.54</td>
</tr>
<tr class="even">
<td align="left">Nursing</td>
<td align="right">1</td>
<td align="right">41</td>
<td align="right">11.94</td>
<td align="right">0.001</td>
<td align="right">15.52</td>
<td align="right">1.35</td>
<td align="right">8.48</td>
<td align="right">1.54</td>
</tr>
<tr class="odd">
<td align="left">Licking_Pups</td>
<td align="right">1</td>
<td align="right">41</td>
<td align="right">1.87</td>
<td align="right">0.179</td>
<td align="right">1.83</td>
<td align="right">0.64</td>
<td align="right">0.81</td>
<td align="right">0.34</td>
</tr>
<tr class="even">
<td align="left">Nest_Building</td>
<td align="right">1</td>
<td align="right">41</td>
<td align="right">0.15</td>
<td align="right">0.705</td>
<td align="right">0.65</td>
<td align="right">0.27</td>
<td align="right">0.81</td>
<td align="right">0.31</td>
</tr>
<tr class="odd">
<td align="left">Eating.Drinking</td>
<td align="right">1</td>
<td align="right">41</td>
<td align="right">0.13</td>
<td align="right">0.716</td>
<td align="right">5.83</td>
<td align="right">0.63</td>
<td align="right">5.52</td>
<td align="right">0.52</td>
</tr>
<tr class="even">
<td align="left">Grooming</td>
<td align="right">1</td>
<td align="right">41</td>
<td align="right">0.14</td>
<td align="right">0.707</td>
<td align="right">9.74</td>
<td align="right">0.68</td>
<td align="right">10.14</td>
<td align="right">0.83</td>
</tr>
<tr class="odd">
<td align="left">Active</td>
<td align="right">1</td>
<td align="right">41</td>
<td align="right">0.76</td>
<td align="right">0.388</td>
<td align="right">131.35</td>
<td align="right">6.22</td>
<td align="right">139.76</td>
<td align="right">7.45</td>
</tr>
<tr class="even">
<td align="left">Resting</td>
<td align="right">1</td>
<td align="right">41</td>
<td align="right">1.24</td>
<td align="right">0.273</td>
<td align="right">168.74</td>
<td align="right">5.00</td>
<td align="right">179.00</td>
<td align="right">7.96</td>
</tr>
</tbody>
</table>
<p>Table 1 reproduces with very small differences probably due to implementation of ANOVA/LMM in different statistical software.</p>
</div>
<div id="glucocorticoid-metabolites-in-mothers" class="section level2">
<h2>Glucocorticoid metabolites in mothers</h2>
<blockquote>
<p>sample sizes for the glucocorticoid metabolites are novel male n=20, familiar male n= 21 and unmated control n= 18. Using a repeated measures ANOVA we found that FGM’s did change significantly over time (effect of time: F2, 112 = 131, p= &lt;0.001; interaction between time and housing companion: F4,112= 29.5, p&lt;0.001).</p>
</blockquote>
<pre class="r"><code># melt wide to long
exp4_long &lt;- melt(exp4, id.vars=c(&quot;ID&quot;, &quot;Treatment&quot;), variable.name=&quot;Time&quot;, value.name=&quot;GCM&quot;)
(fit.aov_4 &lt;- aov_4(GCM ~ Treatment*Time + (Time|ID), data=exp4_long, anova_table = list(correction = &quot;none&quot;)))</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: Treatment</code></pre>
<pre><code>## Anova Table (Type 3 tests)
## 
## Response: GCM
##           Effect     df         MSE          F ges p.value
## 1      Treatment  2, 56 10320601.60     3.98 * .08     .02
## 2           Time 2, 112  3329615.78 131.53 *** .48  &lt;.0001
## 3 Treatment:Time 4, 112  3329615.78  29.54 *** .29  &lt;.0001
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;+&#39; 0.1 &#39; &#39; 1</code></pre>
<p>reproduces</p>
<blockquote>
<p>The was no difference in the FGMs in the females before the experiment began (ANOVA: F2,56=0.094, p= 0.911), but there was following exposure to their partners (ANOVA: F2,56=43.72, p=&lt;0.001) and at the end of the experiment which coincided with mid lactation for the reproducing treatments (F2,56=4.6, p=0.014)(See Figure 3).</p>
</blockquote>
<pre class="r"><code>anova(lm(Collection_1 ~ Treatment, data=exp4))</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: Collection_1
##           Df    Sum Sq Mean Sq F value Pr(&gt;F)
## Treatment  2   1745142  872571  0.0937 0.9107
## Residuals 56 521265047 9308304</code></pre>
<pre class="r"><code>anova(lm(Collection_2 ~ Treatment, data=exp4))</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: Collection_2
##           Df    Sum Sq   Mean Sq F value    Pr(&gt;F)    
## Treatment  2 450542880 225271440  43.722 3.649e-12 ***
## Residuals 56 288531030   5152340                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>anova(lm(Collection_3 ~ Treatment, data=exp4))</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: Collection_3
##           Df    Sum Sq  Mean Sq F value  Pr(&gt;F)  
## Treatment  2  23346970 11673485  4.6338 0.01373 *
## Residuals 56 141074581  2519189                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Reproduces</p>
<blockquote>
<p>After removing the unmated control from the analysis we found that the effect of time was still significant (F2, 78= 143, p=&lt;0.001) but the interaction between time and housing companion was not (F1,78=1.89, p=0.158).</p>
</blockquote>
<pre class="r"><code>aov_4(GCM ~ Treatment*Time + (Time|ID), data=exp4_long[Treatment!=&quot;UC&quot;,], anova_table = list(correction = &quot;none&quot;))</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: Treatment</code></pre>
<pre><code>## Anova Table (Type 3 tests)
## 
## Response: GCM
##           Effect    df        MSE          F ges p.value
## 1      Treatment 1, 39 5499166.40       1.22 .01     .28
## 2           Time 2, 78 4612053.02 143.76 *** .70  &lt;.0001
## 3 Treatment:Time 2, 78 4612053.02       1.89 .03     .16
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;+&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Reproduces</p>
</div>
<div id="fig.-3" class="section level2">
<h2>Fig. 3</h2>
<pre class="r"><code>raw &lt;- exp4_long[!is.na(GCM), .(GCM=mean(GCM),
                     SE=sd(GCM)/sqrt(.N)), by=.(Treatment, Time)]
modeled &lt;- summary(emmeans(fit.aov_4, specs=c(&quot;Treatment&quot;, &quot;Time&quot;)))

pd &lt;- position_dodge(0.5)
gg1 &lt;- ggplot(data=raw, aes(x=Treatment, y=GCM, color=Time, group=Time)) +
  geom_point(position=pd) +
  geom_errorbar(aes(ymin=GCM-SE, ymax=GCM+SE), width=0.2, position=pd) +
  coord_cartesian(ylim=c(0,15000)) + # this is way too much white space
  NULL
gg1</code></pre>
<p><img src="/post/2019-02-18-data-from-perceived-threats-of-infanticide-reduce-maternal-allocation-during-lactation-and-lead-to-elevated-oxidative-damage-in-offspring_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<pre class="r"><code>gg1 &lt;- ggplot(data=modeled, aes(x=Treatment, y=emmean, color=Time, group=Time)) +
  geom_point(position=pd) +
  geom_errorbar(aes(ymin=emmean-SE, ymax=emmean+SE), width=0.2, position=pd) +
  coord_cartesian(ylim=c(0,15000)) + # this is way too much white space
  NULL
gg1</code></pre>
<p><img src="/post/2019-02-18-data-from-perceived-threats-of-infanticide-reduce-maternal-allocation-during-lactation-and-lead-to-elevated-oxidative-damage-in-offspring_files/figure-html/unnamed-chunk-13-2.png" width="672" /></p>
<p>The plot with unconditional SE (raw) reproduces</p>
</div>
<div id="oxidative-stress-in-offspring" class="section level2">
<h2>Oxidative stress in offspring</h2>
<p>Table 2 cannot be reproduced because two of the necessary columns (Sex and Plate) are not available (that I can see) in the Excel file (the analysis is a linear mixed model with Block and Plate as random factors and Treatment and Sex as fixed factors).</p>
</div>
</div>
<div id="statistical-red-flags" class="section level1">
<h1>Statistical Red Flags</h1>
<div id="computation-of-anova-table-using-afex-package" class="section level2">
<h2>1. Computation of ANOVA table using Afex package</h2>
<p>The afex package replicates the SPSS output for the growth rate analysis but the design is very unbalanced. It’s unclear to me how afex handles this; is it like AOV (which doesn’t handle unbalanced data well) or more like anova(lme/lmer), which does handle unbalanced data well (with caveats on Type III interpretation). So I compare the SPSS-like repeated measures anova with lme/lmer and also with simple fixed effects analysis (lm and aov)</p>
<div id="how-balanced-is-the-design" class="section level3">
<h3>How balanced is the design</h3>
<pre class="r"><code># how balanced is design?
exp1_long[!is.na(Weight), .(N=.N), by=.(Treatment, Sex, Time)]</code></pre>
<pre><code>##     Treatment Sex      Time  N
##  1:       LBE   F     birth 48
##  2:       LBE   M     birth 39
##  3:        MC   F     birth 52
##  4:        MC   M     birth 45
##  5:       LBE   F   weaning 48
##  6:       LBE   M   weaning 39
##  7:        MC   F   weaning 52
##  8:        MC   M   weaning 45
##  9:       LBE   F adulthood 48
## 10:       LBE   M adulthood 39
## 11:        MC   F adulthood 52
## 12:        MC   M adulthood 45</code></pre>
</div>
<div id="anova-using-afex-computation-above" class="section level3">
<h3>ANOVA using Afex (computation above)</h3>
<pre class="r"><code>fit.aov_4</code></pre>
<pre><code>## Anova Table (Type 3 tests)
## 
## Response: GCM
##           Effect     df         MSE          F ges p.value
## 1      Treatment  2, 56 10320601.60     3.98 * .08     .02
## 2           Time 2, 112  3329615.78 131.53 *** .48  &lt;.0001
## 3 Treatment:Time 4, 112  3329615.78  29.54 *** .29  &lt;.0001
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;+&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
</div>
<div id="anova-table-using-lmelmer" class="section level2">
<h2>3 ANOVA table using lme/lmer</h2>
<pre class="r"><code># model III anova of lme/lmer fis
contrasts(exp1_long$Treatment) &lt;- contr.sum
contrasts(exp1_long$Sex) &lt;- contr.sum
m1 &lt;- lme(Weight ~ Treatment*Sex*Time, random = ~ 1|ID, data=exp1_long, method = &quot;ML&quot;)
anova(m1, type=&quot;marginal&quot;)</code></pre>
<pre><code>##                    numDF denDF  F-value p-value
## (Intercept)            1   360  373.865  &lt;.0001
## Treatment              1   180    0.000  0.9937
## Sex                    1   180    1.624  0.2042
## Time                   2   360 5670.133  &lt;.0001
## Treatment:Sex          1   180    0.217  0.6421
## Treatment:Time         2   360    7.572  0.0006
## Sex:Time               2   360    1.275  0.2807
## Treatment:Sex:Time     2   360    2.274  0.1044</code></pre>
<pre class="r"><code>m2 &lt;- lmer(Weight ~ Treatment*Sex*Time + (1|ID), data=exp1_long, REML = FALSE)
anova(m2, type=&quot;marginal&quot;)</code></pre>
<pre><code>## Marginal Analysis of Variance Table with Satterthwaite&#39;s method
##                     Sum Sq Mean Sq NumDF DenDF   F value    Pr(&gt;F)    
## Treatment              0.0     0.0     1 506.6    0.0001 0.9935887    
## Sex                    1.7     1.7     1 506.6    1.6599 0.1982049    
## Time               11612.0  5806.0     2 368.0 5796.1325 &lt; 2.2e-16 ***
## Treatment:Sex          0.2     0.2     1 506.6    0.2216 0.6380571    
## Treatment:Time        15.5     7.8     2 368.0    7.7404 0.0005095 ***
## Sex:Time               2.6     1.3     2 368.0    1.3034 0.2728658    
## Treatment:Sex:Time     4.7     2.3     2 368.0    2.3247 0.0992518 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>contrasts(exp1_long$Treatment) &lt;- contr.treatment
contrasts(exp1_long$Sex) &lt;- contr.treatment</code></pre>
<p>If we’re focussing on p-values, then 1) the big difference using lme/lmer compared to Afex (SPSS/SAS like repeated measures anova) is the p-value for Treatment but also 2) another difference is that for Treatment x Sex. That said, it doesn’t make much sense to interpret the Treatment p-value as evidence for “an effect” given the interactions.</p>
<div id="compare-lmm-to-anova-table-using-lm-and-aov-ignoring-clustering-due-to-repeated-measures" class="section level3">
<h3>Compare LMM to ANOVA table using lm() and AOV (ignoring clustering due to repeated measures)</h3>
<pre class="r"><code># fixed effects only
contrasts(exp1_long$Treatment) &lt;- contr.sum
contrasts(exp1_long$Sex) &lt;- contr.sum
# using linear model
Anova(lm(Weight ~ Treatment*Sex*Time, data=exp1_long), type=&quot;3&quot;)</code></pre>
<pre><code>## Anova Table (Type III tests)
## 
## Response: Weight
##                     Sum Sq  Df   F value    Pr(&gt;F)    
## (Intercept)          485.6   1  373.8652 &lt; 2.2e-16 ***
## Treatment              0.0   1    0.0001  0.993659    
## Sex                    2.1   1    1.6238  0.203109    
## Time               11612.0   2 4469.8837 &lt; 2.2e-16 ***
## Treatment:Sex          0.3   1    0.2167  0.641721    
## Treatment:Time        15.5   2    5.9692  0.002728 ** 
## Sex:Time               2.6   2    1.0051  0.366678    
## Treatment:Sex:Time     4.7   2    1.7927  0.167493    
## Residuals            701.4 540                        
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code># classical ANOVA
summary(aov(Weight ~ Treatment*Sex*Time, data=exp1_long))</code></pre>
<pre><code>##                     Df Sum Sq Mean Sq  F value   Pr(&gt;F)    
## Treatment            1     16      16   12.234 0.000508 ***
## Sex                  1      0       0    0.305 0.580994    
## Time                 2  11758    5879 4526.107  &lt; 2e-16 ***
## Treatment:Sex        1     10      10    7.975 0.004917 ** 
## Treatment:Time       2     15       8    5.959 0.002755 ** 
## Sex:Time             2      3       1    1.033 0.356550    
## Treatment:Sex:Time   2      5       2    1.793 0.167493    
## Residuals          540    701       1                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>contrasts(exp1_long$Treatment) &lt;- contr.treatment
contrasts(exp1_long$Sex) &lt;- contr.treatment</code></pre>
</div>
<div id="plot-it-to-visualize-the-effects" class="section level3">
<h3>Plot it to visualize the effects</h3>
<pre class="r"><code># linear mixed model &quot;version&quot; of repeated measures ANOVA 
fit.lme &lt;- lme(Weight ~ Treatment*Sex*Time, random = ~ Time|ID, data=exp1_long, method = &quot;ML&quot;)
coef(summary(fit.lme))</code></pre>
<pre><code>##                                     Value  Std.Error  DF    t-value
## (Intercept)                    1.56461538 0.05825548 360 26.8578212
## Treatment2                    -0.07732372 0.08408455 180 -0.9195948
## Sex2                           0.13665573 0.08552960 180  1.5977595
## Timeweaning                    6.59288462 0.16213903 360 40.6619215
## Timeadulthood                 11.64850000 0.23356384 360 49.8728748
## Treatment2:Sex2                0.15733466 0.12456628 180  1.2630598
## Treatment2:Timeweaning        -0.92955128 0.23402754 360 -3.9719740
## Treatment2:Timeadulthood      -0.60870833 0.33712036 360 -1.8056113
## Sex2:Timeweaning              -0.47815573 0.23804945 360 -2.0086403
## Sex2:Timeadulthood            -0.54977111 0.34291400 360 -1.6032332
## Treatment2:Sex2:Timeweaning    0.29302752 0.34669793 360  0.8451955
## Treatment2:Sex2:Timeadulthood  0.88803073 0.49942384 360  1.7781104
##                                     p-value
## (Intercept)                    5.393345e-88
## Treatment2                     3.590152e-01
## Sex2                           1.118505e-01
## Timeweaning                   1.239816e-136
## Timeadulthood                 9.750687e-164
## Treatment2:Sex2                2.082013e-01
## Treatment2:Timeweaning         8.610403e-05
## Treatment2:Timeadulthood       7.181430e-02
## Sex2:Timeweaning               4.532162e-02
## Sex2:Timeadulthood             1.097601e-01
## Treatment2:Sex2:Timeweaning    3.985631e-01
## Treatment2:Sex2:Timeadulthood  7.622969e-02</code></pre>
<pre class="r"><code>fit.emm &lt;- data.table(summary(emmeans(fit.lme, specs=c(&quot;Treatment&quot;, &quot;Sex&quot;, &quot;Time&quot;))))
setnames(fit.emm, old=&quot;emmean&quot;, new=&quot;Weight&quot;)
pd &lt;- position_dodge(0.5)
gg &lt;- ggplot(data=exp1_long, aes(x=Treatment, y=Weight, color=Time)) +
  #geom_point(position=pd) +
  geom_point(data=fit.emm, aes(x=Treatment, y=Weight), position=pd)+
  geom_errorbar(data=fit.emm, aes(x=Treatment, ymin=lower.CL, ymax=upper.CL), position=pd, width=0.2) +
  facet_grid(.~Sex) +
  NULL
gg</code></pre>
<p><img src="/post/2019-02-18-data-from-perceived-threats-of-infanticide-reduce-maternal-allocation-during-lactation-and-lead-to-elevated-oxidative-damage-in-offspring_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
</div>
</div>
</div>
