---
title: Data from Organic matter and nutrient inputs from large wildlife influence
  ecosystem function in the Mara River, Africa
author: Jeff Walker
date: '2019-01-29'
slug: data-from-organic-matter-and-nutrient-inputs-from-large-wildlife-influence-ecosystem-function-in-the-mara-river-africa
categories: []
tags:
  - ancova
  - one-way anova
  - tukey posthoc
  - ancova slopes posthoc
  - repeated measures anova
  - aov
  - R
  - non-parametric tests
subtitle: ''
output:
  blogdown::html_page:
    toc: true
---


<div id="TOC">
<ul>
<li><a href="#sources">Sources</a></li>
<li><a href="#summary">Summary</a></li>
<li><a href="#caveats">Caveats</a></li>
<li><a href="#set-up">Set up</a></li>
<li><a href="#import">Import</a></li>
<li><a href="#reproducibility">Reproducibility</a><ul>
<li><a href="#nutrient-dissolution-rates">Nutrient dissolution rates</a><ul>
<li><a href="#statistical-methods">Statistical methods</a></li>
<li><a href="#anova-results">ANOVA results</a></li>
<li><a href="#posthoc-pairwise-comparisons">Posthoc pairwise comparisons</a></li>
</ul></li>
<li><a href="#decomposition-rates">Decomposition rates</a><ul>
<li><a href="#statistical-methods-1">Statistical methods</a></li>
<li><a href="#anova-results-1">ANOVA results</a></li>
</ul></li>
<li><a href="#nutrient-limitation">Nutrient limitation</a><ul>
<li><a href="#statistical-method">Statistical method</a></li>
<li><a href="#respiration-results">Respiration Results</a></li>
<li><a href="#chlorophyll-a-results">Chlorophyll a results</a></li>
</ul></li>
<li><a href="#ecosystem-function">Ecosystem Function</a><ul>
<li><a href="#experimental-streams">Experimental Streams</a></li>
<li><a href="#river-biofilms">River Biofilms</a></li>
<li><a href="#section"></a></li>
</ul></li>
</ul></li>
<li><a href="#statistical-red-flags">Statistical red-flags</a></li>
</ul>
</div>

<div id="sources" class="section level1">
<h1>Sources</h1>
<p>Subalusky AL, Dutton CL, Njoroge L, Rosi EJ, Post DM (2018) Organic matter and nutrient inputs from large wildlife influence ecosystem function in the Mara River, Africa. Ecology 99(11): 2558-2574. <a href="https://doi.org/10.1002/ecy.2509" class="uri">https://doi.org/10.1002/ecy.2509</a></p>
<p>Subalusky AL, Dutton CL, Njoroge L, Rosi EJ, Post DM (2018) Data from: Organic matter and nutrient inputs from large wildlife influence ecosystem function in the Mara River, Africa. Dryad Digital Repository. <a href="https://doi.org/10.5061/dryad.g886d9v" class="uri">https://doi.org/10.5061/dryad.g886d9v</a></p>
</div>
<div id="summary" class="section level1">
<h1>Summary</h1>
<ol style="list-style-type: decimal">
<li><p>The files are nearly perfectly clean.</p></li>
<li><p>Nutrient dissolution: The authors do not use repeated measures anova as specified in the methods. The fixed effects ANOVA reproduce the ANOVA table. The post-hoc t-tests are reproduced qualitatively but not quantitatively.</p></li>
<li><p>Decomposition rates: The ANOVA statistics reproduce using the column “ln_hippo_prop_rem”, which is not the column I inferred from either the methods or from the text description of the results.</p></li>
<li><p>Nutrient limitation: Reproduces as specified.</p></li>
<li><p>Ecosystem function: Experimental streams: The response log(GPP) (as specified in methods) does not reproduce but untransformed GPP does reproduce. The response Sqrt(chl) (as specified in methods) does not reproduce but log(chl) does reproduce. The rates of increase reproduce. River biofilms: All analyses reproduce at least qualitatively (I cannot check quantiative results where none were given). Treatment column had to be re-coded in order to reproduce.</p></li>
<li><p>A few minor to moderate statistical red flags are noted.</p></li>
</ol>
</div>
<div id="caveats" class="section level1">
<h1>Caveats</h1>
<p>Failure to reproduce or partial reproducibility might be an error in my coding, or my misunderstanding of the author’s methods, or my lack of knowledge of statistics generally or the R functions that I use more specifically.</p>
</div>
<div id="set-up" class="section level1">
<h1>Set up</h1>
<pre class="r"><code>library(broom)
library(ggplot2)
library(ggpubr)
library(data.table)
library(readxl)
library(nlme)
library(emmeans)</code></pre>
<pre class="r"><code>data_folder &lt;- &quot;../data&quot;
folder &lt;- &quot;Data from Organic matter and nutrient inputs from large wildlife influence ecosystem function in the Mara River, Africa&quot;

# images need to be moved to /static/images/data from.../image.png
knitr_path &lt;- FALSE # run = TRUE to debug</code></pre>
<pre class="r"><code>source(&quot;../R/clean_label.R&quot;) # bookdown</code></pre>
</div>
<div id="import" class="section level1">
<h1>Import</h1>
<pre class="r"><code># dissolution rates
fn &lt;- &quot;Subalusky_2018_mara_nutrient_dissolution_chambers.csv&quot;
file_path &lt;- paste(data_folder, folder, fn, sep=&quot;/&quot;)
dissolution &lt;- fread(file_path)
dissolution[, treatment:=factor(treatment, c(&quot;H 1&quot;, &quot;H 5&quot;, &quot;H 20&quot;, &quot;W&quot;, &quot;HW&quot;))]

# decomposition rates
fn &lt;- &quot;Subalusky_2018_mara_hippo_feces_decomp_litterbags.csv&quot;
file_path &lt;- paste(data_folder, folder, fn, sep=&quot;/&quot;)
decomp &lt;- fread(file_path)
colnames(decomp) &lt;- clean_label(colnames(decomp))
# treatment =   experimental treatment, where A: 40 g fresh hippo feces; B: 10 g aged hippo feces; C: 10 g aged hippo feces + 20 g wildebeest tissue
decomp[, treatment_recode:=ifelse(treatment==&quot;A&quot;, &quot;fresh&quot;,
                                  ifelse(treatment==&quot;B&quot;, &quot;aged&quot;, &quot;wb&quot;))]
decomp[, treatment_recode:=factor(treatment_recode, c(&quot;fresh&quot;, &quot;aged&quot;, &quot;wb&quot;))]

# nutrient limitation
fn &lt;- &quot;Subalusky_2018_mara_nutrient_limitation_assays.csv&quot;
file_path &lt;- paste(data_folder, folder, fn, sep=&quot;/&quot;)
limit &lt;- fread(file_path)

# Ecosystem function
fn &lt;- &quot;Subalusky_2018_mara_experimental_stream_tiles.csv&quot;
file_path &lt;- paste(data_folder, folder, fn, sep=&quot;/&quot;)
stream &lt;- fread(file_path)

# River biofilms
# note there is another file with the raw data. This is the file of means from that file.
fn &lt;- &quot;Subalusky_2018_mara_river_biofilm_summary_data.csv&quot;
file_path &lt;- paste(data_folder, folder, fn, sep=&quot;/&quot;)
river &lt;- fread(file_path)</code></pre>
</div>
<div id="reproducibility" class="section level1">
<h1>Reproducibility</h1>
<div id="nutrient-dissolution-rates" class="section level2">
<h2>Nutrient dissolution rates</h2>
<div id="statistical-methods" class="section level3">
<h3>Statistical methods</h3>
<blockquote>
<p>We analyzed each of the four response variables (NH4, SRP, DOC and DO) in response to treatment and time using a repeated measures ANOVA with the aov function in R (R Core Team 2018).</p>
</blockquote>
<p>Note there is no column for the random factor, which should be chamber, since there were three time measures within each chamber. I created one assuming that the order is uniform.</p>
<pre class="r"><code># add chamber ID, this assumes chamber order is maintained
dissolution[, chamber:=paste(treatment, rep(1:3), sep=&quot;-&quot;)]</code></pre>
</div>
<div id="anova-results" class="section level3">
<h3>ANOVA results</h3>
<pre class="r"><code>summary(aov(log(NH4.no0) ~ treatment*hours + Error(chamber), data=dissolution))$&quot;Error: chamber&quot;</code></pre>
<pre><code>##           Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## treatment  4  95.77  23.943   36.41 6.22e-06 ***
## Residuals 10   6.58   0.658                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>summary(aov(log(SRP.no0) ~ treatment*hours + Error(chamber), data=dissolution))$&quot;Error: chamber&quot;</code></pre>
<pre><code>##           Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## treatment  4  327.0   81.75   224.5 9.64e-10 ***
## Residuals 10    3.6    0.36                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>summary(aov(log(DOC.no0) ~ treatment*hours + Error(chamber), data=dissolution))$&quot;Error: chamber&quot;</code></pre>
<pre><code>##           Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## treatment  4 250.12   62.53    14.9 0.000323 ***
## Residuals 10  41.97    4.20                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<blockquote>
<p>There were significant treatment effects of input type and concentration on NH4 (rm ANOVA, F=23.53<span class="math inline">\(_{4,35}\)</span>, P&lt;0.001), SRP (F=123.61<span class="math inline">\(_{4,35}\)</span>, P&lt;0.001), and DOC (F=27.96<span class="math inline">\(_{4,35}\)</span>, P&lt;0.001), and significant treatment by time interaction effects on NH4 (rm ANOVA, interaction, F=9.304,35, P&lt;0.001) and SRP (F=7.594,35, P&lt;0.001).</p>
</blockquote>
<blockquote>
<p>There were also significant treatment effects on DO (rm ANOVA, F=101.69<span class="math inline">\(_{4,35}\)</span>, P&lt;0.001)</p>
</blockquote>
<p>This does not reproduce.</p>
<p>After some exploration, a simple fixed effects model reproduces, so this is not a repeated measures ANOVA, which raises Statistical Red Flag #1 (see below)</p>
<pre class="r"><code>nh4.fit &lt;- lm(log(NH4.no0) ~ treatment*hours, data=dissolution)
srp.fit &lt;- lm(log(SRP.no0) ~ treatment*hours, data=dissolution)
doc.fit &lt;- lm(log(DOC.no0) ~ treatment*hours, data=dissolution)
do.fit &lt;- lm(log(DO) ~ treatment*hours, data=dissolution)

summary(aov(nh4.fit))</code></pre>
<pre><code>##                 Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## treatment        4  95.77   23.94  23.526 1.65e-09 ***
## hours            1 112.97  112.97 110.995 2.13e-12 ***
## treatment:hours  4  37.87    9.47   9.302 3.14e-05 ***
## Residuals       35  35.62    1.02                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>summary(aov(srp.fit))</code></pre>
<pre><code>##                 Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## treatment        4  327.0   81.75 123.610  &lt; 2e-16 ***
## hours            1    5.8    5.84   8.835 0.005317 ** 
## treatment:hours  4   20.1    5.02   7.592 0.000163 ***
## Residuals       35   23.1    0.66                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>summary(aov(doc.fit))</code></pre>
<pre><code>##                 Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## treatment        4 250.12   62.53  27.963 1.81e-10 ***
## hours            1   8.84    8.84   3.952   0.0547 .  
## treatment:hours  4   7.91    1.98   0.885   0.4831    
## Residuals       35  78.27    2.24                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>summary(aov(do.fit))</code></pre>
<pre><code>##                 Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## treatment        4  32.87   8.218 101.687 &lt; 2e-16 ***
## hours            1   1.48   1.477  18.269 0.00014 ***
## treatment:hours  4   0.57   0.142   1.762 0.15864    
## Residuals       35   2.83   0.081                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="posthoc-pairwise-comparisons" class="section level3">
<h3>Posthoc pairwise comparisons</h3>
<blockquote>
<p>If there was a significant treatment effect at α=0.05, we then performed a Tukey pairwise comparison test between treatments using the Holm method to adjust p values for multiple comparisons (Holm 1979, R Core Team 2018).</p>
</blockquote>
<p>Note that “Tukey pairwise comparison” is a specific kind of simultaneous posthoc test not the general name for post hoc tests. And, it’s not clear what this analysis is, especially given the large interaction for NH4, which makes pairwise comparisons conditional on the level of time. So are the comparisons at 24 hours? Or, was there complete pooling across time?</p>
<p>Here is the Holm adjustment using the pooled sigma from the fixed effect model for NH4. This isn’t close to the reported pattern of significance levels.</p>
<pre class="r"><code>nh4.emm &lt;- emmeans(nh4.fit, specs=&quot;treatment&quot;)</code></pre>
<pre><code>## NOTE: Results may be misleading due to involvement in interactions</code></pre>
<pre class="r"><code>contrast(nh4.emm, method=&quot;revpairwise&quot;, adjust=&quot;holm&quot;) # caution! ignores interaction</code></pre>
<pre><code>##  contrast      estimate        SE df t.ratio p.value
##  H 5 - H 1   1.19769259 0.4755705 35   2.518  0.0660
##  H 20 - H 1  2.78786429 0.4755705 35   5.862  &lt;.0001
##  H 20 - H 5  1.59017170 0.4755705 35   3.344  0.0099
##  W - H 1     3.72439891 0.4755705 35   7.831  &lt;.0001
##  W - H 5     2.52670632 0.4755705 35   5.313  &lt;.0001
##  W - H 20    0.93653462 0.4755705 35   1.969  0.1706
##  HW - H 1    3.66837140 0.4755705 35   7.714  &lt;.0001
##  HW - H 5    2.47067881 0.4755705 35   5.195  0.0001
##  HW - H 20   0.88050711 0.4755705 35   1.851  0.1706
##  HW - W     -0.05602751 0.4755705 35  -0.118  0.9069
## 
## Results are given on the log (not the response) scale. 
## P value adjustment: holm method for 10 tests</code></pre>
<p>Here I use pairwise t-test using both the pooled SD over all groups and the pooled SD for the two groups compared. Regardless, this raises Statistical Red Flag #2.</p>
<pre class="r"><code>pairwise.t.test(x=log(dissolution$NH4.no0), g=dissolution$treatment, p.adjust.method=&quot;holm&quot;, pool.sd=TRUE)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  log(dissolution$NH4.no0) and dissolution$treatment 
## 
##      H 1    H 5    H 20   W     
## H 5  0.9850 -      -      -     
## H 20 0.0732 0.6304 -      -     
## W    0.0073 0.1214 1.0000 -     
## HW   0.0077 0.1214 1.0000 1.0000
## 
## P value adjustment method: holm</code></pre>
<pre class="r"><code>pairwise.t.test(x=log(dissolution$SRP.no0), g=dissolution$treatment, p.adjust.method=&quot;holm&quot;, pool.sd=TRUE)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  log(dissolution$SRP.no0) and dissolution$treatment 
## 
##      H 1     H 5     H 20    W     
## H 5  2.5e-05 -       -       -     
## H 20 1.9e-09 0.0068  -       -     
## W    1.7e-15 2.3e-09 2.5e-05 -     
## HW   1.3e-15 1.9e-09 2.5e-05 0.8814
## 
## P value adjustment method: holm</code></pre>
<pre class="r"><code>pairwise.t.test(x=log(dissolution$DOC.no0), g=dissolution$treatment, p.adjust.method=&quot;holm&quot;, pool.sd=TRUE)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  log(dissolution$DOC.no0) and dissolution$treatment 
## 
##      H 1     H 5     H 20    W      
## H 5  0.00238 -       -       -      
## H 20 6.8e-06 0.10160 -       -      
## W    1.1e-09 0.00014 0.02949 -      
## HW   1.1e-09 0.00014 0.02949 0.97000
## 
## P value adjustment method: holm</code></pre>
<pre class="r"><code>pairwise.t.test(x=log(dissolution$NH4.no0), g=dissolution$treatment, p.adjust.method=&quot;holm&quot;, pool.sd=FALSE)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with non-pooled SD 
## 
## data:  log(dissolution$NH4.no0) and dissolution$treatment 
## 
##      H 1   H 5   H 20  W    
## H 5  1.000 -     -     -    
## H 20 0.262 1.000 -     -    
## W    0.032 0.234 1.000 -    
## HW   0.032 0.234 1.000 1.000
## 
## P value adjustment method: holm</code></pre>
<pre class="r"><code>pairwise.t.test(x=log(dissolution$SRP.no0), g=dissolution$treatment, p.adjust.method=&quot;holm&quot;, pool.sd=FALSE)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with non-pooled SD 
## 
## data:  log(dissolution$SRP.no0) and dissolution$treatment 
## 
##      H 1    H 5     H 20    W     
## H 5  0.0188 -       -       -     
## H 20 0.0019 1.0e-05 -       -     
## W    0.0001 1.1e-09 3.8e-16 -     
## HW   0.0001 2.8e-10 9.7e-15 0.3472
## 
## P value adjustment method: holm</code></pre>
<pre class="r"><code>pairwise.t.test(x=log(dissolution$DOC.no0), g=dissolution$treatment, p.adjust.method=&quot;holm&quot;, pool.sd=FALSE)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with non-pooled SD 
## 
## data:  log(dissolution$DOC.no0) and dissolution$treatment 
## 
##      H 1    H 5     H 20    W     
## H 5  0.0774 -       -       -     
## H 20 0.0162 5.4e-09 -       -     
## W    0.0023 3.5e-08 1.5e-05 -     
## HW   0.0023 3.7e-08 1.5e-05 0.9144
## 
## P value adjustment method: holm</code></pre>
<p>note – the design is balanced so Welch t-test would be the same</p>
<blockquote>
<p>Concentrations of NH4, SRP and DOC increased with increasing hippo feces concentration, although treatment differences were only significant for SRP and DOC (except for low and medium concentrations for DOC) (pairwise t test, P&lt;0.05 for all comparisons).</p>
</blockquote>
<p>the qualitative pattern reproduces except:</p>
<p>using pool.sd=TRUE, DOC:H5 v H20 &gt; 0.05, not H1 v H5</p>
<p>using pool.sd=FALSE, DOC: H5 v H20 &lt; 0.05 and H1 v H5 &lt; 0.05</p>
<blockquote>
<p>The wildebeest treatment was significantly higher in NH4 than the lowest concentration of hippo feces (P=0.017), and it was significantly higher in SRP and DOC than all concentrations of hippo feces (P&lt;0.05 for all comparisons).</p>
</blockquote>
<p>qualitatively reproduces except:</p>
<p>using pool.sd=TRUE, NH4: w v H1, p= 0.0073, reported = (P=0.017)</p>
<p>using pool.sd=FALSE, NH4: w v H1, p=0.0023, reported = (P=0.017)</p>
<blockquote>
<p>There were no significant differences between the wildebeest and hippo + wb treatments for NH4 or DOC; however, SRP was higher in the hippo + wb treatment as compared to the wildebeest treatment (p&lt;0.03)</p>
</blockquote>
<p>The w vs. wb treatment does not reproduce for SRP &gt; There was no significant difference in oxygen consumption between the high concentration of hippo feces, wildebeest and hippo + wb treatments.</p>
<pre class="r"><code>pairwise.t.test(x=log(dissolution$DO), g=dissolution$treatment, p.adjust.method=&quot;holm&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  log(dissolution$DO) and dissolution$treatment 
## 
##      H 1     H 5     H 20 W
## H 5  1.9e-08 -       -    -
## H 20 5.4e-15 1.5e-05 -    -
## W    2.6e-15 6.6e-06 1    -
## HW   2.7e-15 6.6e-06 1    1
## 
## P value adjustment method: holm</code></pre>
<p>This pattern reproduces using the non-pooled sigma (independent t-tests).</p>
</div>
</div>
<div id="decomposition-rates" class="section level2">
<h2>Decomposition rates</h2>
<div id="statistical-methods-1" class="section level3">
<h3>Statistical methods</h3>
<blockquote>
<p>We used a two-way ANOVA to analyze the influence of treatment (fresh, aged, with wildebeest) on decay rate. Presence of an interaction effect between treatment and time at α=0.05 indicated a significant effect of treatment on decay rate. We then conducted pairwise analyses of each treatment combination using one-way ANOVAs to determine how they differed from one another. We accounted for the number of pairwise comparison tests by using a Bonferroni adjusted α value of 0.0167 to indicate statistical significance. All statistical analyses in this paper were done in R version 3.3.2 (R Core Team 2018).</p>
</blockquote>
</div>
<div id="anova-results-1" class="section level3">
<h3>ANOVA results</h3>
<blockquote>
<p>There was a significant interaction between hippo feces treatment and time on the mass remaining (two-way ANOVA, interaction, F=3.19<span class="math inline">\(_2{},75}\)</span>, P=0.047), indicating an effect of treatment on decay rate (Table 1, Appendix S2: Fig. S2).</p>
</blockquote>
<pre class="r"><code>hippo_post &lt;- lm(hippo_post ~ treatment_recode*days, data=decomp)
summary(aov(hippo_post))</code></pre>
<pre><code>##                       Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## treatment_recode       2   82.1    41.1  23.329 1.32e-08 ***
## days                   1  448.0   448.0 254.549  &lt; 2e-16 ***
## treatment_recode:days  2   32.0    16.0   9.078 0.000295 ***
## Residuals             75  132.0     1.8                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>This doesn’t reproduce. What does reproduce is using the column “ln_hippo_prop_rem”, which is the log of the column “adj_hippo_prop_rem”. So the response it is not the “mass remaining” but the log of the adjusted proportion of the mass remaining. This raises Statistical Red Flag #3.</p>
<pre class="r"><code>decomp[, my_ln_hippo_prop_rem:=log(adj_hippo_prop_rem)]
head(decomp[, .SD, .SDcols=c(&quot;ln_hippo_prop_rem&quot;, &quot;my_ln_hippo_prop_rem&quot;)])</code></pre>
<pre><code>##    ln_hippo_prop_rem my_ln_hippo_prop_rem
## 1:        0.00000000           0.00000000
## 2:        0.00000000           0.00000000
## 3:        0.00000000           0.00000000
## 4:        0.14335032           0.14335032
## 5:       -0.01834045          -0.01834045
## 6:       -0.17065323          -0.17065323</code></pre>
<pre class="r"><code>ln_hippo_prop_rem.fit &lt;- lm(ln_hippo_prop_rem ~ treatment_recode*days, data=decomp)
summary(aov(ln_hippo_prop_rem.fit))</code></pre>
<pre><code>##                       Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## treatment_recode       2   2.62    1.31  11.213 5.49e-05 ***
## days                   1  40.53   40.53 346.773  &lt; 2e-16 ***
## treatment_recode:days  2   0.75    0.37   3.192   0.0467 *  
## Residuals             75   8.76    0.12                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<blockquote>
<p>Fresh feces decayed faster than aged hippo feces (ANOVA, interaction, F=4.21<span class="math inline">\(_{1,56}\)</span>, P=0.045), although this was not significant after accounting for multiple comparisons. There was no significant difference between decay rate of fresh feces and aged feces with carcass (ANOVA, interaction, F=0.18<span class="math inline">\(_{1,49}\)</span>, P=0.671); however, aged feces with carcass decayed significantly faster than aged feces alone (ANOVA, interaction, F=8.20<span class="math inline">\(_{1,45}\)</span>, P=0.006).</p>
</blockquote>
<p>This reproduces (using “ln_hippo_prop_rem”) but the independent ANOVAs raises Statistical Red Flag #4</p>
<pre class="r"><code>fit &lt;- lm(ln_hippo_prop_rem ~ treatment_recode*days, data=decomp[treatment_recode!=&quot;wb&quot;])
summary(aov(fit))</code></pre>
<pre><code>##                       Df Sum Sq Mean Sq F value Pr(&gt;F)    
## treatment_recode       1   0.78    0.78   5.849 0.0189 *  
## days                   1  31.96   31.96 240.167 &lt;2e-16 ***
## treatment_recode:days  1   0.56    0.56   4.205 0.0450 *  
## Residuals             56   7.45    0.13                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>fit &lt;- lm(ln_hippo_prop_rem ~ treatment_recode*days, data=decomp[treatment_recode!=&quot;aged&quot;])
summary(aov(fit))</code></pre>
<pre><code>##                       Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## treatment_recode       1   2.58    2.58  17.257 0.00013 ***
## days                   1  31.63   31.63 211.920 &lt; 2e-16 ***
## treatment_recode:days  1   0.03    0.03   0.183 0.67080    
## Residuals             49   7.31    0.15                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>fit &lt;- lm(ln_hippo_prop_rem ~ treatment_recode*days, data=decomp[treatment_recode!=&quot;fresh&quot;])
summary(aov(fit))</code></pre>
<pre><code>##                       Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## treatment_recode       1  0.594   0.594   9.663 0.00326 ** 
## days                   1 17.862  17.862 290.813 &lt; 2e-16 ***
## treatment_recode:days  1  0.504   0.504   8.198 0.00635 ** 
## Residuals             45  2.764   0.061                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
</div>
<div id="nutrient-limitation" class="section level2">
<h2>Nutrient limitation</h2>
<div id="statistical-method" class="section level3">
<h3>Statistical method</h3>
<blockquote>
<p>Data were square-root transformed to meet assumptions of normality. We used a two-way ANOVA to analyze the response of biofilms to different nutrient treatments at different sites in both 2011 and 2013. If there were significant interactions at α=0.05, we then used one-way ANOVAs to analyze treatment responses separately for each site, followed by Tukey’s HSD post-hoc test for multiple comparisons (R Core Team 2018).</p>
</blockquote>
</div>
<div id="respiration-results" class="section level3">
<h3>Respiration Results</h3>
<blockquote>
<p>Respiration (R) by heterotrophic biofilms responded differently to nutrient treatments at sites with and without large wildlife inputs in both 2011 (two-way ANOVA, interaction, F=5.40<span class="math inline">\(_{10,68}\)</span>, P&lt;0.001) and 2013 (F=3.67<span class="math inline">\(_{12,75}\)</span>, P&lt;0.001).</p>
</blockquote>
<p>Reproduces</p>
<pre class="r"><code># heterotrophic: substrate = &quot;Sponge&quot;
R_hetero_Y11.fit &lt;- lm(sqrt(CR.corr.no0) ~ treatment*site, data=limit[year==&quot;2011&quot; &amp; substrate==&quot;Sponge&quot;])
summary(aov(R_hetero_Y11.fit))</code></pre>
<pre><code>##                Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## treatment       5   1.93    0.39   1.952    0.097 .  
## site            2  64.84   32.42 163.743  &lt; 2e-16 ***
## treatment:site 10  10.85    1.09   5.481 6.33e-06 ***
## Residuals      68  13.46    0.20                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>R_hetero_Y13.fit &lt;- lm(sqrt(CR.corr.no0) ~ treatment*site, data=limit[year==&quot;2013&quot; &amp; substrate==&quot;Sponge&quot;])
summary(aov(R_hetero_Y13.fit))</code></pre>
<pre><code>##                Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## treatment       6   0.50   0.083   1.177 0.327927    
## site            2  39.59  19.793 279.248  &lt; 2e-16 ***
## treatment:site 12   3.12   0.260   3.666 0.000241 ***
## Residuals      75   5.32   0.071                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div id="site-1" class="section level4">
<h4>Site 1</h4>
<blockquote>
<p>At the No Wildlife site in 2011, R on the organic substrate increased significantly relative to the control in response to NH4+PO4 and to NO3+PO4 (one-way ANOVA, F=18.52$_{5,24}, P&lt;0.001; Tukey’s HSD, P=0.005 and P&lt;0.001, respectively), but not in response to any of the nutrients alone, indicating N and P co-limitation (Appendix S2: Fig. S3).</p>
</blockquote>
<p>Reproduces</p>
<pre class="r"><code># site key: Site 1=&quot;no wildlife&quot;, Site 2=&quot;Hippo&quot;, Site 3=&quot;Hippo + wildebeast&quot;
# nutrients added to agar cup; Ctl: control, C: carbon (only measured in 2013), H: ammonium, N: nitrate, P: phosphate, HP: ammonium + phosphate, NP: nitrate + phosphate
fit &lt;- lm(sqrt(CR.corr.no0) ~ treatment, data=limit[year==&quot;2011&quot; &amp; substrate==&quot;Sponge&quot; &amp; site==&quot;Site 1&quot;])
summary(aov(fit))</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## treatment    5  7.404   1.481   18.52 1.53e-07 ***
## Residuals   24  1.919   0.080                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>TukeyHSD(aov(fit))$treatment[c(&quot;HP-Ctl&quot;, &quot;NP-Ctl&quot;),]</code></pre>
<pre><code>##             diff       lwr      upr        p adj
## HP-Ctl 0.7255561 0.1725791 1.278533 0.0054021017
## NP-Ctl 0.9652852 0.4123081 1.518262 0.0001996743</code></pre>
<pre class="r"><code>TukeyHSD(aov(fit))$treatment[c(&quot;H-Ctl&quot;, &quot;N-Ctl&quot;, &quot;P-Ctl&quot;),]</code></pre>
<pre><code>##             diff        lwr        upr     p adj
## H-Ctl -0.1634622 -0.7164392 0.38951490 0.9390785
## N-Ctl -0.4680626 -1.0210396 0.08491448 0.1315282
## P-Ctl  0.1725193 -0.3804578 0.72549636 0.9246336</code></pre>
<blockquote>
<p>At the No Wildlife site in 2013, R increased significantly relative to the control in response to carbon (C), NH4+PO4 and PO4 (one-way ANOVA, F=19.22<span class="math inline">\(_{6,21}\)</span>, P&lt;0.001; Tukey’s HSD, P=0.006, P&lt;0.001, and P&lt;0.001, respectively). R did not increase in response to NH4 alone, or in response to PO4 in combination with NO3, suggesting primary P limitation with some N and P co-limitation along with C limitation</p>
</blockquote>
<pre class="r"><code>fit &lt;- lm(sqrt(CR.corr.no0) ~ treatment, data=limit[year==&quot;2013&quot; &amp; substrate==&quot;Sponge&quot; &amp; site==&quot;Site 1&quot;])
summary(aov(fit))</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## treatment    6 2.0800  0.3467   19.22 1.57e-07 ***
## Residuals   21 0.3787  0.0180                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>TukeyHSD(aov(fit))$treatment[c(&quot;Ctl-C&quot;, &quot;HP-Ctl&quot;, &quot;P-Ctl&quot;),]</code></pre>
<pre><code>##              diff        lwr         upr        p adj
## Ctl-C  -0.3835365 -0.6763715 -0.09070153 5.488410e-03
## HP-Ctl  0.6153914  0.3393039  0.89147886 7.147611e-06
## P-Ctl   0.8134293  0.4946310  1.13222768 8.622235e-07</code></pre>
<pre class="r"><code>TukeyHSD(aov(fit))$treatment[c(&quot;N-Ctl&quot;, &quot;NP-Ctl&quot;),]</code></pre>
<pre><code>##             diff        lwr       upr     p adj
## N-Ctl  0.1545214 -0.1383135 0.4473564 0.6139750
## NP-Ctl 0.2052370 -0.1135614 0.5240353 0.3917952</code></pre>
<p>Reproduces</p>
</div>
<div id="site-2-and-3" class="section level4">
<h4>Site 2 and 3</h4>
<blockquote>
<p>There were no significant effects of nutrient treatment on R at either the Hippo site or the Hippo + WB site, suggesting no nutrient limitation at those sites.</p>
</blockquote>
<pre class="r"><code>fit &lt;- lm(sqrt(CR.corr.no0) ~ treatment, data=limit[year==&quot;2011&quot; &amp; substrate==&quot;Sponge&quot; &amp; site==&quot;Site 2&quot;])
summary(aov(fit))</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)  
## treatment    5  3.487  0.6974    2.74 0.0427 *
## Residuals   24  6.109  0.2545                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>TukeyHSD(aov(fit))$treatment[c(&quot;H-Ctl&quot;, &quot;P-Ctl&quot;, &quot;N-Ctl&quot;, &quot;HP-Ctl&quot;, &quot;NP-Ctl&quot;),]</code></pre>
<pre><code>##               diff       lwr        upr      p adj
## H-Ctl  -0.49651970 -1.483107 0.49006782 0.63336376
## P-Ctl  -0.07406682 -1.060654 0.91252071 0.99989444
## N-Ctl  -0.41929163 -1.405879 0.56729590 0.77462304
## HP-Ctl -0.74287951 -1.729467 0.24370802 0.22181349
## NP-Ctl -0.96445944 -1.951047 0.02212809 0.05799027</code></pre>
<pre class="r"><code>fit &lt;- lm(sqrt(CR.corr.no0) ~ treatment, data=limit[year==&quot;2013&quot; &amp; substrate==&quot;Sponge&quot; &amp; site==&quot;Site 2&quot;])
summary(aov(fit))</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## treatment    6  0.614 0.10233   1.205  0.334
## Residuals   27  2.294 0.08495</code></pre>
<pre class="r"><code>TukeyHSD(aov(fit))$treatment[c(&quot;H-Ctl&quot;, &quot;P-Ctl&quot;, &quot;N-Ctl&quot;, &quot;HP-Ctl&quot;, &quot;NP-Ctl&quot;),]</code></pre>
<pre><code>##               diff        lwr       upr     p adj
## H-Ctl  -0.09253428 -0.7144362 0.5293677 0.9990057
## P-Ctl  -0.42720580 -1.0491077 0.1946962 0.3358384
## N-Ctl  -0.23418011 -0.8560821 0.3877218 0.8889358
## HP-Ctl -0.28117407 -0.9030760 0.3407279 0.7768327
## NP-Ctl -0.16702455 -0.7889265 0.4548774 0.9763263</code></pre>
<p>Reproduces</p>
<pre class="r"><code>fit &lt;- lm(sqrt(CR.corr.no0) ~ treatment, data=limit[year==&quot;2011&quot; &amp; substrate==&quot;Sponge&quot; &amp; site==&quot;Site 3&quot;])
summary(aov(fit))</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## treatment    5  1.732  0.3465   1.275  0.313
## Residuals   20  5.436  0.2718</code></pre>
<pre class="r"><code>TukeyHSD(aov(fit))$treatment[c(&quot;H-Ctl&quot;, &quot;P-Ctl&quot;, &quot;N-Ctl&quot;, &quot;HP-Ctl&quot;, &quot;NP-Ctl&quot;),]</code></pre>
<pre><code>##              diff       lwr       upr     p adj
## H-Ctl  -0.5478455 -1.647137 0.5514464 0.6281603
## P-Ctl  -0.2787022 -1.315125 0.7577201 0.9550266
## N-Ctl  -0.1351988 -1.171621 0.9012236 0.9982755
## HP-Ctl -0.6566995 -1.853457 0.5400579 0.5322726
## NP-Ctl -0.6763893 -1.775681 0.4229026 0.4116556</code></pre>
<pre class="r"><code>fit &lt;- lm(sqrt(CR.corr.no0) ~ treatment, data=limit[year==&quot;2013&quot; &amp; substrate==&quot;Sponge&quot; &amp; site==&quot;Site 3&quot;])
summary(aov(fit))</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## treatment    6  1.067 0.17790   1.817  0.133
## Residuals   27  2.644 0.09792</code></pre>
<pre class="r"><code>TukeyHSD(aov(fit))$treatment[c(&quot;H-Ctl&quot;, &quot;P-Ctl&quot;, &quot;N-Ctl&quot;, &quot;HP-Ctl&quot;, &quot;NP-Ctl&quot;),]</code></pre>
<pre><code>##              diff        lwr       upr     p adj
## H-Ctl  -0.3457392 -0.9752268 0.2837483 0.5924224
## P-Ctl  -0.3238252 -0.9533128 0.3056623 0.6612798
## N-Ctl  -0.3354401 -0.9649276 0.2940475 0.6249464
## HP-Ctl  0.0346985 -0.6329739 0.7023709 0.9999979
## NP-Ctl -0.1357190 -0.7652065 0.4937686 0.9923498</code></pre>
<p>Reproduces</p>
</div>
</div>
<div id="chlorophyll-a-results" class="section level3">
<h3>Chlorophyll a results</h3>
<blockquote>
<p>There was no significant interaction between site and treatment for chl a in either 2011 (two-way ANOVA, interaction, F=1.92<span class="math inline">\(_{10,71}\)</span>, P=0.057) or 2013 (F=1.02<span class="math inline">\(_{12,77}\)</span>, P=0.444).</p>
</blockquote>
<pre class="r"><code>Chlor_hetero_Y11.fit &lt;- lm(sqrt(Chl.corr.no0) ~ treatment*site, data=limit[year==&quot;2011&quot; &amp; substrate==&quot;Glass&quot;])
summary(aov(Chlor_hetero_Y11.fit))</code></pre>
<pre><code>##                Df Sum Sq Mean Sq F value Pr(&gt;F)    
## treatment       5  0.391   0.078   2.158 0.0684 .  
## site            2  7.673   3.837 105.777 &lt;2e-16 ***
## treatment:site 10  0.697   0.070   1.920 0.0563 .  
## Residuals      71  2.575   0.036                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>Chlor_hetero_Y13.fit &lt;- lm(sqrt(Chl.corr.no0) ~ treatment*site, data=limit[year==&quot;2013&quot; &amp; substrate==&quot;Glass&quot;])
summary(aov(Chlor_hetero_Y13.fit))</code></pre>
<pre><code>##                Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## treatment       6 0.4478  0.0746   2.471  0.0308 *  
## site            2 1.8047  0.9023  29.873 2.5e-10 ***
## treatment:site 12 0.3692  0.0308   1.018  0.4409    
## Residuals      77 2.3259  0.0302                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Reproduces</p>
<blockquote>
<p>At the No Wildlife site in 2011, chl a on the inorganic substrate increased significantly relative to the control in response to NH4 (one-way ANOVA, F=3.47$_{5,24}, P=0.017; Tukey’s HSD, P=0.031), suggesting some N limitation (Appendix S2: Fig. S3). There were no significant effects of nutrients on chl a at either the Hippo site or the Hippo + WB site.</p>
</blockquote>
<pre class="r"><code>fit &lt;- lm(sqrt(Chl.corr.no0) ~ treatment, data=limit[year==&quot;2011&quot; &amp; substrate==&quot;Glass&quot; &amp; site==&quot;Site 1&quot;])
summary(aov(fit))</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)  
## treatment    5 0.4439 0.08878   3.465 0.0169 *
## Residuals   24 0.6150 0.02562                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>TukeyHSD(aov(fit))$treatment[c(&quot;H-Ctl&quot;, &quot;P-Ctl&quot;, &quot;N-Ctl&quot;, &quot;HP-Ctl&quot;, &quot;NP-Ctl&quot;),]</code></pre>
<pre><code>##               diff         lwr       upr     p adj
## H-Ctl   0.33476567  0.02173257 0.6477988 0.0312101
## P-Ctl  -0.04833751 -0.36137060 0.2646956 0.9965348
## N-Ctl   0.12354627 -0.18948683 0.4365794 0.8227697
## HP-Ctl  0.10840744 -0.20462566 0.4214405 0.8880863
## NP-Ctl  0.06721617 -0.24581693 0.3802493 0.9842836</code></pre>
<p>Reproduces</p>
</div>
</div>
<div id="ecosystem-function" class="section level2">
<h2>Ecosystem Function</h2>
<div id="experimental-streams" class="section level3">
<h3>Experimental Streams</h3>
<div id="statistical-methods-2" class="section level4">
<h4>Statistical methods</h4>
<blockquote>
<p>We transformed the data to meet assumptions of normality using log transformations for GPP and R and square root transformations for AFDM and chl a. We analyzed each of the four response variables (GPP, R, AFDM and chl a) throughout the duration of the experiment using a linear mixed-effect model run with the lme function in the nlme package in R (Pinheiro et al. 2016, R Core Team 2018). We fitted lme models with the restricted maximum likelihood method and a continuous autoregressive temporal correlation structure with day as the repeated factor. Treatment (control, hippo, wb, hippo+wb) and time (each of 4 weeks of measurement) were treated as fixed effects, and individual streams were treated as random effects. A significant interaction between treatment and time indicated different rates of biofilm growth by treatment. We then used lstrends in the lsmeans package to perform a Tukey pairwise comparison test between treatments for biofilm parameters over the duration of the experiment (Lenth 2016, R Core Team 2018). We also used one-way ANOVAs to analyze differences in standing stock biofilm parameters by treatment in the final week of the experiment.</p>
</blockquote>
</div>
<div id="results" class="section level4">
<h4>Results</h4>
<blockquote>
<p>The rate of biofilm growth in experimental streams was influenced by the presence of wildlife inputs. There was a significant interaction between treatment and time for GPP (lme, interaction effect, F=3.03<span class="math inline">\(_{3,32}\)</span>, P=0.044)</p>
</blockquote>
<pre class="r"><code>fit &lt;- lme(log(GPP.no0) ~ treatment*days, random = ~ 1|id, correlation=corCAR1(form = ~ days | id), data=stream, method=&quot;REML&quot;)
anova(fit, type=&quot;marginal&quot;)</code></pre>
<pre><code>##                numDF denDF   F-value p-value
## (Intercept)        1    32 0.0358325  0.8511
## treatment          3     8 2.3139503  0.1525
## days               1    32 0.8916191  0.3521
## treatment:days     3    32 1.1330431  0.3505</code></pre>
<pre class="r"><code>fit &lt;- lme((GPP.no0) ~ treatment*days, random = ~ 1|id, correlation=corCAR1(form = ~ days | id), data=stream, method=&quot;REML&quot;)
anova(fit, type=&quot;marginal&quot;)</code></pre>
<pre><code>##                numDF denDF   F-value p-value
## (Intercept)        1    32 0.1959720  0.6610
## treatment          3     8 1.0404178  0.4256
## days               1    32 0.7817183  0.3832
## treatment:days     3    32 3.0308241  0.0435</code></pre>
<p>log(GPP) (as specified in methods) does not reproduce but untransformed GPP (or GPP.no0) does reproduce. This makes a difference if using the p-value to guide further analyses.</p>
<pre class="r"><code>fit &lt;- lme((GPP.no0) ~ treatment*days, random = ~ 1|id, correlation=corCAR1(form = ~ days | id), data=stream, method=&quot;REML&quot;)
anova(fit, type=&quot;marginal&quot;)</code></pre>
<pre><code>##                numDF denDF   F-value p-value
## (Intercept)        1    32 0.1959720  0.6610
## treatment          3     8 1.0404178  0.4256
## days               1    32 0.7817183  0.3832
## treatment:days     3    32 3.0308241  0.0435</code></pre>
<blockquote>
<p>There was a significant interaction between treatment and time for … chl a (lme, interaction effect, F=3.44<span class="math inline">\(_{3,32}\)</span>, P=0.028)</p>
</blockquote>
<pre class="r"><code>fit &lt;- lme(sqrt(Chl) ~ treatment*days, random = ~ 1|id, correlation=corCAR1(form = ~ days | id), data=stream, method=&quot;REML&quot;)
anova(fit, type=&quot;marginal&quot;)</code></pre>
<pre><code>##                numDF denDF   F-value p-value
## (Intercept)        1    32  1.037504  0.3160
## treatment          3     8  0.742392  0.5561
## days               1    32 12.825500  0.0011
## treatment:days     3    32  4.007184  0.0157</code></pre>
<pre class="r"><code>fit &lt;- lme((Chl) ~ treatment*days, random = ~ 1|id, correlation=corCAR1(form = ~ days | id), data=stream, method=&quot;REML&quot;)
anova(fit, type=&quot;marginal&quot;)</code></pre>
<pre><code>##                numDF denDF  F-value p-value
## (Intercept)        1    32 0.656122  0.4239
## treatment          3     8 1.064214  0.4167
## days               1    32 3.010976  0.0923
## treatment:days     3    32 4.959265  0.0061</code></pre>
<pre class="r"><code>fit &lt;- lme(log(Chl) ~ treatment*days, random = ~ 1|id, correlation=corCAR1(form = ~ days | id), data=stream, method=&quot;REML&quot;)
anova(fit, type=&quot;marginal&quot;)</code></pre>
<pre><code>##                numDF denDF   F-value p-value
## (Intercept)        1    32 167.65293  &lt;.0001
## treatment          3     8   0.75683  0.5489
## days               1    32  60.05165  &lt;.0001
## treatment:days     3    32   3.44368  0.0281</code></pre>
<p>Sqrt(chl) (as specified in methods) does not reproduce. Untransformed chl does not reproduce. Log(chl) does reproduce.</p>
<blockquote>
<p>The rate of increase was greatest in the Hippo + WB treatment as compared to the Control for both GPP (lstrends pairwise comparison, t ratio: -2.7632, P=0.044) and chl a (lstrends pairwise comparison, t ratio:-3.0832, P=0.021).</p>
</blockquote>
<pre class="r"><code># use the models that reproduce, not the models specified in methods
m1 &lt;- lme((GPP.no0) ~ treatment*days, random = ~ 1|id, correlation=corCAR1(form = ~ days | id), data=stream, method=&quot;REML&quot;)
emtrends(m1, pairwise ~ treatment, var = &quot;days&quot;)</code></pre>
<pre><code>## $emtrends
##  treatment        days.trend      SE df   lower.CL  upper.CL
##  Control            1.701172 1.92408 32 -2.2180500  5.620393
##  Hippo              2.580315 1.92408 32 -1.3389068  6.499537
##  Hippo Wildebeest   9.205480 1.92408 32  5.2862584 13.124702
##  Wildebeest         4.531453 1.92408 32  0.6122316  8.450675
## 
## Trends are based on the ( (transformed) scale 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast                        estimate       SE df t.ratio p.value
##  Control - Hippo               -0.8791432 2.721059 32  -0.323  0.9881
##  Control - Hippo Wildebeest    -7.5043084 2.721059 32  -2.758  0.0448
##  Control - Wildebeest          -2.8302817 2.721059 32  -1.040  0.7274
##  Hippo - Hippo Wildebeest      -6.6251652 2.721059 32  -2.435  0.0907
##  Hippo - Wildebeest            -1.9511385 2.721059 32  -0.717  0.8896
##  Hippo Wildebeest - Wildebeest  4.6740267 2.721059 32   1.718  0.3314
## 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<pre class="r"><code>m2 &lt;- lme(log(Chl) ~ treatment*days, random = ~ 1|id, correlation=corCAR1(form = ~ days | id), data=stream, method=&quot;REML&quot;)
emtrends(m2, pairwise ~ treatment, var = &quot;days&quot;)</code></pre>
<pre><code>## $emtrends
##  treatment        days.trend         SE df  lower.CL  upper.CL
##  Control           0.1888508 0.02437005 32 0.1392106 0.2384910
##  Hippo             0.2231760 0.02437005 32 0.1735358 0.2728162
##  Hippo Wildebeest  0.2951255 0.02437005 32 0.2454853 0.3447657
##  Wildebeest        0.2173685 0.02437005 32 0.1677284 0.2670087
## 
## Trends are based on the log (transformed) scale 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast                          estimate         SE df t.ratio p.value
##  Control - Hippo               -0.034325184 0.03446445 32  -0.996  0.7528
##  Control - Hippo Wildebeest    -0.106274698 0.03446445 32  -3.084  0.0207
##  Control - Wildebeest          -0.028517706 0.03446445 32  -0.827  0.8410
##  Hippo - Hippo Wildebeest      -0.071949514 0.03446445 32  -2.088  0.1788
##  Hippo - Wildebeest             0.005807478 0.03446445 32   0.169  0.9983
##  Hippo Wildebeest - Wildebeest  0.077756992 0.03446445 32   2.256  0.1300
## 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<p>Reproduces.</p>
</div>
</div>
<div id="river-biofilms" class="section level3">
<h3>River Biofilms</h3>
<div id="statistical-methods-3" class="section level4">
<h4>Statistical methods</h4>
<blockquote>
<p>Data were normally distributed with equal variance among sites, so we used a one-way ANOVA followed by Tukey’s HSD test for pairwise comparisons to test for differences among sites (R Core Team 2018). We then used independent t-tests to analyze differences in chl a and AFDM (for which we had sufficient data) by site with and without the presence of wildebeest carcasses at the Hippo + WB site. There were no significant differences between seasons for any of the three sites, so we then used a one-way ANOVA followed by Tukey’s HSD test to test for differences between the No Wildlife site, the Hippo site, the Hippo + WB site with carcasses and the Hippo + WB site without carcasses.</p>
</blockquote>
</div>
<div id="results-1" class="section level4">
<h4>Results</h4>
<blockquote>
<p>GPP (n=4 per site) increased from the No Wildlife site to the Hippo site but was lowest at the Hippo + WB site (Fig. 6)</p>
</blockquote>
<pre class="r"><code>site_levels &lt;- c(&quot;No Wildlife&quot;, &quot;Hippo&quot;, &quot;Hippo + WB&quot;)
river[, site_fac:=factor(ifelse(site==&quot;Site 1&quot;, site_levels[1],
                           ifelse(site==&quot;Site 2&quot;, site_levels[2], site_levels[3])),
                           site_levels)
                           ]
fit &lt;- lm(GPP ~ site_fac, data=river)
(fit.emm &lt;- emmeans(fit, specs=&quot;site_fac&quot;))</code></pre>
<pre><code>##  site_fac      emmean       SE df   lower.CL upper.CL
##  No Wildlife 2.953233 1.141321  9  0.3713848 5.535081
##  Hippo       5.745391 1.141321  9  3.1635430 8.327239
##  Hippo + WB  1.671208 1.141321  9 -0.9106396 4.253056
## 
## Confidence level used: 0.95</code></pre>
<pre class="r"><code>contrast(fit.emm, method=&quot;revpairwise&quot;)</code></pre>
<pre><code>##  contrast                  estimate       SE df t.ratio p.value
##  Hippo - No Wildlife       2.792158 1.614072  9   1.730  0.2468
##  Hippo + WB - No Wildlife -1.282024 1.614072  9  -0.794  0.7157
##  Hippo + WB - Hippo       -4.074183 1.614072  9  -2.524  0.0758
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p>reproduces qualitatively (cannot check quantitative)</p>
<blockquote>
<p>Chl a (n=6-8 per site) followed the same pattern, increasing from the No Wildlife site to the Hippo site (not significant), then decreasing from the Hippo site to the Hippo + WB site (one-way ANOVA, F=9.44<span class="math inline">\(_{2,19}\)</span>, P=0.001; Tukey’s HSD: P=0.001) (Fig. 6).</p>
</blockquote>
<pre class="r"><code>fit &lt;- lm(Chl ~ site_fac, data=river)
anova(fit)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: Chl
##           Df   Sum Sq  Mean Sq F value   Pr(&gt;F)   
## site_fac   2 0.087329 0.043665  9.4363 0.001426 **
## Residuals 19 0.087919 0.004627                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>(fit.emm &lt;- emmeans(fit, specs=&quot;site_fac&quot;))</code></pre>
<pre><code>##  site_fac        emmean         SE df     lower.CL   upper.CL
##  No Wildlife 0.12675582 0.02405021 19  0.076418160 0.17709348
##  Hippo       0.20849813 0.02777079 19  0.150373209 0.26662306
##  Hippo + WB  0.04929859 0.02405021 19 -0.001039075 0.09963625
## 
## Confidence level used: 0.95</code></pre>
<pre class="r"><code>contrast(fit.emm, method=&quot;revpairwise&quot;)</code></pre>
<pre><code>##  contrast                    estimate         SE df t.ratio p.value
##  Hippo - No Wildlife       0.08174231 0.03673730 19   2.225  0.0924
##  Hippo + WB - No Wildlife -0.07745724 0.03401213 19  -2.277  0.0837
##  Hippo + WB - Hippo       -0.15919955 0.03673730 19  -4.333  0.0010
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p>Reproduces.</p>
<blockquote>
<p>There was also a significant difference in chl a when comparing by site and season (one-way ANOVA, F=5.99<span class="math inline">\(_{3,18}\)</span>, P=0.005). The Hippo + WB site had significantly lower chl a than the Hippo site both when carcasses were present (Tukey’s HSD: P=0.015) and when they were not (Tukey’s HSD: P=0.009); however, there was no difference between the Hippo + WB site with and without carcasses (Tukey’s HSD: P=0.996).</p>
</blockquote>
<pre class="r"><code># river[, .(Chl=mean(Chl), N=.N), by=.(site.wb)]
# fit &lt;- lm(Chl ~ site.wb, data=river)
# anova(fit)
# (fit.emm &lt;- emmeans(fit, specs=&quot;site.wb&quot;))
# contrast(fit.emm, method=&quot;revpairwise&quot;)

river[, site.wb2:=ifelse(site!=&quot;Site 3&quot;, site, site.wb)]
fit &lt;- lm(Chl ~ site.wb2, data=river)
anova(fit)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: Chl
##           Df   Sum Sq   Mean Sq F value   Pr(&gt;F)   
## site.wb2   3 0.087559 0.0291864  5.9911 0.005133 **
## Residuals 18 0.087689 0.0048716                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>(fit.emm &lt;- emmeans(fit, specs=&quot;site.wb2&quot;))</code></pre>
<pre><code>##  site.wb2           emmean         SE df    lower.CL  upper.CL
##  Site 1         0.12675582 0.02467688 18  0.07491161 0.1786000
##  Site 2         0.20849813 0.02849441 18  0.14863360 0.2683627
##  Site 3 - no wb 0.04393550 0.03489838 18 -0.02938328 0.1172543
##  Site 3 - wb    0.05466167 0.03489838 18 -0.01865711 0.1279805
## 
## Confidence level used: 0.95</code></pre>
<pre class="r"><code>contrast(fit.emm, method=&quot;revpairwise&quot;)</code></pre>
<pre><code>##  contrast                        estimate         SE df t.ratio p.value
##  Site 2 - Site 1               0.08174231 0.03769456 18   2.169  0.1699
##  Site 3 - no wb - Site 1      -0.08282032 0.04274161 18  -1.938  0.2479
##  Site 3 - no wb - Site 2      -0.16456263 0.04505362 18  -3.653  0.0090
##  Site 3 - wb - Site 1         -0.07209415 0.04274161 18  -1.687  0.3589
##  Site 3 - wb - Site 2         -0.15383646 0.04505362 18  -3.415  0.0149
##  Site 3 - wb - Site 3 - no wb  0.01072617 0.04935377 18   0.217  0.9962
## 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<p>Reproduces. However, the column “site.wb” is not coded correctly for this and I had to recode the column to reproduce.</p>
<blockquote>
<p>Both R (n=4 per site) and AFDM (n=6-7 per site) also increased from the No Wildlife site to the Hippo site (not significant). However, R and AFDM were very similar between the Hippo site and the Hippo + WB site.</p>
</blockquote>
<pre class="r"><code>fit &lt;- lm(CR ~ site_fac, data=river)
anova(fit)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: CR
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## site_fac   2 1.8268 0.91339  2.5353 0.1339
## Residuals  9 3.2425 0.36027</code></pre>
<pre class="r"><code>(fit.emm &lt;- emmeans(fit, specs=&quot;site_fac&quot;))</code></pre>
<pre><code>##  site_fac        emmean        SE df  lower.CL    upper.CL
##  No Wildlife -0.6957567 0.3001145  9 -1.374663 -0.01685062
##  Hippo       -1.4178005 0.3001145  9 -2.096707 -0.73889440
##  Hippo + WB  -1.5990238 0.3001145  9 -2.277930 -0.92011767
## 
## Confidence level used: 0.95</code></pre>
<pre class="r"><code>contrast(fit.emm, method=&quot;revpairwise&quot;)</code></pre>
<pre><code>##  contrast                   estimate        SE df t.ratio p.value
##  Hippo - No Wildlife      -0.7220438 0.4244259  9  -1.701  0.2568
##  Hippo + WB - No Wildlife -0.9032671 0.4244259  9  -2.128  0.1388
##  Hippo + WB - Hippo       -0.1812233 0.4244259  9  -0.427  0.9054
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<pre class="r"><code>fit &lt;- lm(AFDM ~ site_fac, data=river)
anova(fit)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: AFDM
##           Df   Sum Sq   Mean Sq F value Pr(&gt;F)
## site_fac   2 0.013404 0.0067020  1.5617 0.2401
## Residuals 16 0.068665 0.0042916</code></pre>
<pre class="r"><code>(fit.emm &lt;- emmeans(fit, specs=&quot;site_fac&quot;))</code></pre>
<pre><code>##  site_fac       emmean         SE df   lower.CL  upper.CL
##  No Wildlife 0.1231336 0.02476054 16 0.07064362 0.1756236
##  Hippo       0.1825391 0.02674444 16 0.12584338 0.2392347
##  Hippo + WB  0.1726380 0.02674444 16 0.11594230 0.2293336
## 
## Confidence level used: 0.95</code></pre>
<pre class="r"><code>contrast(fit.emm, method=&quot;revpairwise&quot;)</code></pre>
<pre><code>##  contrast                    estimate         SE df t.ratio p.value
##  Hippo - No Wildlife       0.05940544 0.03644652 16   1.630  0.2622
##  Hippo + WB - No Wildlife  0.04950436 0.03644652 16   1.358  0.3852
##  Hippo + WB - Hippo       -0.00990108 0.03782234 16  -0.262  0.9630
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p>Qualitatively reproduces.</p>
</div>
</div>
<div id="section" class="section level3">
<h3></h3>
</div>
</div>
</div>
<div id="statistical-red-flags" class="section level1">
<h1>Statistical red-flags</h1>
<ol style="list-style-type: decimal">
<li><p>The reported statistics do not account for the clustered (non-independent) responses (contra the methods, which states that a repeated measures ANOVA was used).</p></li>
<li><p>Independent t-tests or t-tests using the pooled SD are different models than the original fit model with different coefficients and estimates of the original error. The recommended best practice is posthoc tests using the fit model.</p></li>
<li><p>Proportions have max variance at 0.5 and log transforms are not best practice. Instead logit or arcsine transforms are a better practice for proportions. Also, the value of adj_hippo_prop_rem for row 4 is 1.1541341, which is not allowed for proportions (so one cannot take the arcsin or logit of this)</p></li>
<li><p>The indepdendent ANOVAs are different models than the initial ANOVA with different model coefficients and estimates of the residual error (sigma). The recommended best practice is a posthoc test using the original full model.</p></li>
</ol>
<pre class="r"><code># original model with log transform but simulataneous pairwise comparison
m1 &lt;- lm(ln_hippo_prop_rem ~ treatment_recode*days, data=decomp)
emtrends(m1, pairwise ~ treatment_recode, var = &quot;days&quot;, adjust=&quot;none&quot;)</code></pre>
<pre><code>## $emtrends
##  treatment_recode  days.trend          SE df    lower.CL    upper.CL
##  fresh            -0.03736580 0.002668978 75 -0.04268267 -0.03204892
##  aged             -0.02836847 0.003127220 75 -0.03459821 -0.02213873
##  wb               -0.03994258 0.004616349 75 -0.04913882 -0.03074634
## 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast         estimate          SE df t.ratio p.value
##  fresh - aged -0.008997324 0.004111320 75  -2.188  0.0318
##  fresh - wb    0.002576783 0.005332366 75   0.483  0.6303
##  aged - wb     0.011574106 0.005575857 75   2.076  0.0413</code></pre>
<pre class="r"><code># &quot;none&quot; is used because the authors compare to the bonferroni 0.05/3

# what about arcsin transform? - very different
decomp[, adj_hippo_prop_rem_2:=ifelse(adj_hippo_prop_rem &gt; 1, 1, adj_hippo_prop_rem)]
m2 &lt;- lm(asin(adj_hippo_prop_rem_2) ~ treatment_recode*days, data=decomp)
emtrends(m2, pairwise ~ treatment_recode, var = &quot;days&quot;, adjust=&quot;none&quot;)</code></pre>
<pre><code>## $emtrends
##  treatment_recode  days.trend          SE df    lower.CL    upper.CL
##  fresh            -0.01971311 0.002160026 75 -0.02401611 -0.01541012
##  aged             -0.01732022 0.002530885 75 -0.02236200 -0.01227844
##  wb               -0.02561110 0.003736049 75 -0.03305369 -0.01816851
## 
## Trends are based on the asin (transformed) scale 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast         estimate          SE df t.ratio p.value
##  fresh - aged -0.002392895 0.003327325 75  -0.719  0.4743
##  fresh - wb    0.005897988 0.004315527 75   1.367  0.1758
##  aged - wb     0.008290882 0.004512587 75   1.837  0.0701</code></pre>
<pre class="r"><code># using plot() m2 is better than m1

# what about original log transform but with corrected adj_hippo_prop_rem? - not much different from original
m1b &lt;- lm(log(adj_hippo_prop_rem_2) ~ treatment_recode*days, data=decomp)
emtrends(m1b, pairwise ~ treatment_recode, var = &quot;days&quot;, adjust=&quot;none&quot;)</code></pre>
<pre><code>## $emtrends
##  treatment_recode  days.trend          SE df    lower.CL    upper.CL
##  fresh            -0.03711786 0.002661837 75 -0.04242051 -0.03181521
##  aged             -0.02836847 0.003118852 75 -0.03458154 -0.02215540
##  wb               -0.03994258 0.004603996 75 -0.04911421 -0.03077095
## 
## Trends are based on the log (transformed) scale 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast         estimate          SE df t.ratio p.value
##  fresh - aged -0.008749385 0.004100319 75  -2.134  0.0361
##  fresh - wb    0.002824722 0.005318097 75   0.531  0.5969
##  aged - wb     0.011574106 0.005560937 75   2.081  0.0408</code></pre>
</div>
